## Site Configuration File ##
# name of the folder that the site will be generated in
name = "notion"

# the notion.so page to being parsing from. This page will become the index.html
# of the generated site, and loconotion will parse all sub-pages present on the page
page = "https://kira-network.notion.site/KIRA-Testnet-6b82f68117b4480faeef8192ce9a31f1" 

# optionally apply notion's dark mode, remove the line below to use the default light mode
# theme = "dark"

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Meta Tags ##
  # defined as an array of tables (double square brackets)
  # each key in the table maps to an atttribute in the tag
  # the following adds the tag <meta name="title" content="Loconotion Test Site"/>
  [[site.meta]]
  name = "testnet"
  content = "KIRA | Testnet"
  [[site.meta]]
  name = "description"
  content = "Public testnet page of the kira.network"
  [[site.inject.head.link]]
  rel="icon"
  sizes="192x192"
  type="image/png"
  href="https://ipfs.kira.network/ipfs/QmRqfyEvBoSj6sapjyhQqTJfwQPmsDkMQrxyqtTC6bZcTU"

## Individual Page Settings ##
# the [pages] table defines override settings for individual pages, by defining
# a sub-table named after the page url (or part of the url, but careful about
# not using a string that appears in multiple page urls)
[pages]
  # Page Roles-Permissions
  # This page uses a database to store permissions. Permissions are backlinked throughout the documentation 
  # therefore "no-links" might actually not work here because of necessity to create the permission's page for all exisiting backlinks.
  [pages.1cde3b7e9e7a4734a0e9981f2014447a]
    no-links = true